; PlatformIO Project Configuration File
; Phase 2: ESP32 IoT Cloud Architecture - Day 2 / Session 2

[env:esp32dev]
platform = espressif32@^6.5.0           ; Core industrial Espressif 32-bit driver platform
board = esp32dev                        ; Hardware registers abstraction layer for WROOM-32
framework = arduino                     ; Framework core layer for 32-bit registers
monitor_speed = 115200 

lib_ignore =
    WiFi101
    WiFiNINA
    WiFiNINA_-_Adafruit_Fork                 ; Native high-speed serial baud rate for ESP32 metrics

; --- Remote Over-The-Air (OTA) Deployment Core Configurations ---
upload_protocol = espota
upload_port = 10.206.250.199
upload_flags = --port=3232

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.15
    ESP32Async/ESPAsyncWebServer @ ^3.6.0  
    ESP32Async/AsyncTCP @ ^3.3.2                    
    madhephaestus/ESP32Servo @ ^3.0.6
    adafruit/Adafruit MQTT Library @ ^2.5.9 